import { createHash } from "node:crypto";
import { readFileSync, existsSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { articleSchema } from "@/knowledge/schema";
import { loadKnowledge, parseFrontMatter, processArticle, renderMarkdown, validateArticles, PILOT_BODY_SHA256 } from "@/knowledge/content";
const metadata={title:"A Valid Title",subtitle:null,slug:"a-valid-title",description:"Description",section:"canon",language:"en",status:"ready",order:5,publishedAt:null,updatedAt:"2026-07-28",authors:["capsorix-editorial"],concepts:[],methods:[],related:[],image:null,imageAlt:null,canonicalPath:"/knowledge/canon/a-valid-title"};
const source=(overrides:Record<string,unknown>={},body="# A Valid Title\n\nText")=>{const d={...metadata,...overrides};const lines=Object.entries(d).map(([k,v])=>Array.isArray(v)?(v.length?`${k}:\n${v.map(x=>`  - "${x}"`).join("\n")}`:`${k}: []`):v===null?`${k}: null`:typeof v==="number"?`${k}: ${v}`:`${k}: "${v}"`);return `---\n${lines.join("\n")}\n---\n${body}`};
describe("knowledge content validation",()=>{
 it("accepts valid front matter",()=>expect(processArticle(source()).slug).toBe("a-valid-title"));
 it("rejects missing required metadata",()=>expect(()=>articleSchema.parse({...metadata,title:undefined})).toThrow());
 it("rejects duplicate slugs",()=>{const a=processArticle(source());expect(()=>validateArticles([a,{...a,order:6}])).toThrow(/Duplicate slug/)});
 it("rejects duplicate order",()=>{const a=processArticle(source());expect(()=>validateArticles([a,{...a,slug:"another",canonicalPath:"/knowledge/canon/another"}])).toThrow(/Duplicate order/)});
 it("allows sparse ordering with order 9 absent",()=>expect(validateArticles([processArticle(source({order:10}))])[0].order).toBe(10));
 it("rejects canonical path mismatch",()=>expect(()=>processArticle(source({canonicalPath:"/wrong"}))).toThrow());
 it("rejects published content without publishedAt",()=>expect(()=>processArticle(source({status:"published"}))).toThrow());
 it("rejects image and alt mismatch",()=>expect(()=>processArticle(source({image:"/x.webp"}))).toThrow());
 it("rejects unresolved relationships",()=>{const a=processArticle(source({related:["missing"]}));expect(()=>validateArticles([a])).toThrow(/Unresolved/)});
 it("rejects multiple body H1 headings",()=>expect(()=>processArticle(source({},"# A Valid Title\n# Again"))).toThrow(/Multiple/));
 it("rejects an H1/title mismatch",()=>expect(()=>processArticle(source({},"# Different"))).toThrow(/match/));
 it("supports a missing body H1",()=>expect(processArticle(source({},"## Opening\nText")).hasBodyH1).toBe(false));
 it("renders GFM tables responsively",()=>expect(renderMarkdown("| A | B |\n|---|---|\n| 1 | 2 |").html).toContain("<table>"));
 it("renders standard footnotes",()=>expect(renderMarkdown("Claim[^1]\n\n[^1]: Note").html).toContain('class="footnotes"'));
 it("preserves Unicode superscripts",()=>expect(renderMarkdown("Evidence¹ and finding²").html).toContain("Evidence¹"));
 it("escapes unsafe raw HTML",()=>expect(renderMarkdown('<script>alert("x")</script>').html).not.toContain("<script>"));
 it("preserves the pilot body SHA-256",()=>{const raw=readFileSync("content/knowledge/en/canon/05-the-decisions-a-system-makes-before-anyone-agrees-to-them.md","utf8");const {body}=parseFrontMatter(raw);expect(createHash("sha256").update(body).digest("hex")).toBe(PILOT_BODY_SHA256)});
 it("loads every available canonical position in order",()=>{const k=loadKnowledge();expect(k.articles.map(a=>a.order)).toEqual([1,2,3,4,5,6,7,8,10]);expect(k.collection.totalSize).toBe(10)});
 it("keeps canonical position 9 reserved and unavailable",()=>expect(loadKnowledge().collection.reserved).toEqual([{order:9,title:"Designing Products That Don’t Exist Yet",slug:"designing-products-that-dont-exist-yet",status:"unavailable"}]));
 it("generates complete static article HTML",()=>{const p="dist/knowledge/canon/the-decisions-a-system-makes-before-anyone-agrees-to-them/index.html";if(existsSync(p))expect(readFileSync(p,"utf8")).toContain("Technology as a settled claim about the world")});
 it("retains the pilot as ready",()=>expect(loadKnowledge().articles.find(a=>a.order===5)?.status).toBe("ready"));
 it("exposes every imported published article to RSS generation",()=>expect(loadKnowledge().articles.filter(a=>a.status==="published").map(a=>a.order)).toEqual([1,2,3,4,6,7,10]));
 it("keeps existing production routes declared",()=>{const app=readFileSync("src/App.tsx","utf8");for(const route of ["/ios","/android","/web","/about","/careers"])expect(app).toContain(`path="${route}"`) });
});
