import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { loadKnowledge, PILOT_BODY_SHA256 } from "./content";
import type { KnowledgeArticle } from "./schema";
const site="https://capsorix.tech";
const virtualManifestId = "virtual:knowledge-manifest";
const resolvedVirtualManifestId = `\0${virtualManifestId}`;
const deepFreeze = <T>(value: T): T => {if(value && typeof value==="object" && !Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))deepFreeze(child);}return value;};
const escape=(s:string)=>s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function seo(html:string, route:string,title:string,description:string,robots:string,type="website",graph:object[]=[]){const url=site+route;html=html.replace(/<title>.*?<\/title>/s,`<title>${escape(title)}</title>`).replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${escape(description)}">`).replace(/<meta name="robots"[^>]*>/,`<meta name="robots" content="${robots}">`).replace(/<link rel="canonical"[^>]*>/,`<link rel="canonical" href="${url}">`).replace(/<meta property="og:type"[^>]*>/,`<meta property="og:type" content="${type}">`).replace(/<meta property="og:url"[^>]*>/,`<meta property="og:url" content="${url}">`).replace(/<meta property="og:title"[^>]*>/,`<meta property="og:title" content="${escape(title)}">`).replace(/<meta property="og:description"[^>]*>/,`<meta property="og:description" content="${escape(description)}">`).replace(/<meta name="twitter:title"[^>]*>/,`<meta name="twitter:title" content="${escape(title)}">`).replace(/<meta name="twitter:description"[^>]*>/,`<meta name="twitter:description" content="${escape(description)}">`);const base=[{"@type":"Organization","@id":`${site}/#organization`,name:"Capsorix",url:`${site}/`},{"@type":"WebSite","@id":`${site}/#website`,url:`${site}/`,name:"Capsorix",publisher:{"@id":`${site}/#organization`}}];return html.replace("</head>",`<script id="route-jsonld" type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@graph":[...base,...graph]})}</script></head>`);}
const breadcrumbs=(route:string,name:string)=>({"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Knowledge",item:`${site}/knowledge`},{"@type":"ListItem",position:2,name:route==="/knowledge/canon"?name:"Canon",item:`${site}/knowledge/canon`},...(route==="/knowledge/canon"?[]:[{"@type":"ListItem",position:3,name,item:site+route}]) ]});
function writePage(dist:string,route:string,html:string,content:string){html=html.replace('<div id="root"></div>',`<div id="root">${content}</div>`);const dir=path.join(dist,route.replace(/^\//,""));mkdirSync(dir,{recursive:true});writeFileSync(path.join(dir,"index.html"),html);}
function staticArticle(a:KnowledgeArticle,total:number){return `<main id="main" class="knowledge-static"><article><p>Article ${a.order} of ${total}</p><header><p>${escape(a.description)}</p><p>${a.readingMinutes} min read</p><p>Concepts: ${a.concepts.map(escape).join(" · ")}</p><p>Methods: ${a.methods.map(escape).join(" · ")}</p></header><nav aria-label="Table of contents"><ol>${a.toc.map(x=>`<li><a href="#${x.id}">${escape(x.text)}</a></li>`).join("")}</ol></nav><div class="knowledge-prose">${a.html}</div></article></main>`;}
export function knowledgeBuildPlugin():Plugin {const knowledge=deepFreeze(loadKnowledge());const pilot=knowledge.articles.find(a=>a.order===5);if(pilot?.bodyHash!==PILOT_BODY_SHA256)throw new Error(`Pilot body integrity failure: ${pilot?.bodyHash}`);const manifestSource=`const freeze=value=>{if(value&&typeof value==="object"&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value))freeze(child)}return value};\nexport const collection = freeze(${JSON.stringify(knowledge.collection)});\nexport const articles = freeze(${JSON.stringify(knowledge.articles)});\n`;return {name:"capsorix-knowledge-build",resolveId(id){if(id===virtualManifestId)return resolvedVirtualManifestId;},load(id){if(id===resolvedVirtualManifestId)return manifestSource;},writeBundle(){const dist=path.resolve("dist"),base=readFileSync(path.join(dist,"index.html"),"utf8");const landingTitle="Knowledge | Capsorix",landingDesc="The Capsorix institutional knowledge system for Canon, Concepts, Methods, Research, Projects, and Cases.";let h=seo(base,"/knowledge",landingTitle,landingDesc,"index,follow","website",[{"@type":"CollectionPage",name:landingTitle,url:`${site}/knowledge`},breadcrumbs("/knowledge","Knowledge")]);writePage(dist,"/knowledge",h,`<main id="main"><h1>Knowledge for decisions that outlast delivery.</h1><p>${landingDesc}</p><p>Only the foundational Canon architecture is active today.</p></main>`);const canonDesc="The ordered foundational Canon of the Capsorix Knowledge Platform.";h=seo(base,"/knowledge/canon","Foundational Canon | Capsorix",canonDesc,"index,follow","website",[{"@type":"CollectionPage",name:"Foundational Canon",url:`${site}/knowledge/canon`},breadcrumbs("/knowledge/canon","Canon")]);writePage(dist,"/knowledge/canon",h,`<main id="main"><h1>Foundational Canon</h1><ol>${knowledge.articles.map(a=>`<li>Article ${a.order} of ${knowledge.collection.totalSize}: ${escape(a.title)}</li>`).join("")}<li>Article 9: Designing Products That Don’t Exist Yet — unavailable</li></ol></main>`);for(const a of knowledge.articles){const title=`${a.title} | Capsorix`;const graph=[{"@type":"Article",headline:a.title,description:a.description,url:site+a.canonicalPath,mainEntityOfPage:site+a.canonicalPath,author:{"@id":`${site}/#organization`},publisher:{"@id":`${site}/#organization`},dateModified:a.updatedAt},breadcrumbs(a.canonicalPath,a.title)];h=seo(base,a.canonicalPath,title,a.description,a.status==="ready"?"noindex,follow":"index,follow","article",graph);writePage(dist,a.canonicalPath,h,staticArticle(a,knowledge.collection.totalSize));}
const articleUrls=knowledge.articles.map(a=>`  <url><loc>${site+a.canonicalPath}</loc></url>`).join("\n");const sitemap=readFileSync(path.join(dist,"sitemap.xml"),"utf8").replace("</urlset>",`  <url><loc>${site}/knowledge</loc></url>\n  <url><loc>${site}/knowledge/canon</loc></url>\n${articleUrls}\n</urlset>`);writeFileSync(path.join(dist,"sitemap.xml"),sitemap);const published=knowledge.articles.filter(a=>a.status==="published");writeFileSync(path.join(dist,"knowledge/rss.xml"),`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Capsorix Knowledge</title><link>${site}/knowledge</link><description>Published Capsorix institutional knowledge.</description>${published.map(a=>`<item><title>${escape(a.title)}</title><link>${site+a.canonicalPath}</link><guid>${site+a.canonicalPath}</guid></item>`).join("")}</channel></rss>`);}};}
